form ::= (atribute | function | rule | 'class_attributes' | oo_attributes | 'class_methods') '.'

oo_attributes ::= oo_attribute (';' oo_attributes | )

oo_attribute ::= (oo_modifier | ) oo_var

oo_modifier ::= oo_visibility oo_access | oo_visibility | oo_access

oo_visibility ::= 'public' | 'protected' | 'private'

oo_access ::= 'static' | 'final' | 'static' 'final'

oo_var ::= (atom | ) var ('=' exprs |)

function ::= function_clauses

function_clauses ::= function_clause ( | function_clauses )

function_clause ::= atom clause_args clause_guard (clause_body|)